language: node_js
cache: yarn
script:
  - yarn lint
  - yarn test
before_install:
  - ./ssh.sh
after_success:
  - ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_NAME: Travis CI
  - COMMIT_AUTHOR_EMAIL: travis@gh-pages
