language: node_js
cache:
  yarn: true
  directories:
  - "~/bin"
  - "~/opt"
before_install:
- mkdir tmp
before_script:
- bash ./deploy/travis_setup.sh
script:
- yarn lint
- yarn ci:test
- yarn ci:build:static
after_success:
- bash ./deploy/publish_to_npm.sh
- bash ./deploy/deploy_to_ghpages.sh
- bash ./deploy/deploy_to_gcp.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: travis@gh-pages
  - COMMIT_AUTHOR_NAME: Travis CI
  - SOURCE_BRANCH: master
