language: node_js
cache: yarn
script:
- yarn lint
- yarn test
- bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: 5890ad0da7e1
  - COMMIT_AUTHOR_EMAIL: travis@gh-pages
# before_install:
# - openssl aes-256-cbc -K $encrypted_5890ad0da7e1_key -iv $encrypted_5890ad0da7e1_iv
#   -in publish-key.enc -out publish-key -d
