language: node_js
cache:
  yarn: true
  directories:
  - "~/bin"
  - "~/opt"
before_script:
- yarn global add lerna
- yarn global add babel-cli
- yarn ci:setup
script:
- yarn ci:test
- yarn lint
- yarn build:packages
after_success:
- yarn publish:packages
- yarn publish:site
env:
  global:
  - SOURCE_BRANCH: master
  - STORAGE_BUCKET: axiom.platform-prod.gcp0.bwcom.net
