language: node_js
cache: yarn
script:
  - yarn lint
  - yarn test
before_install:
  - bash ./ssh.sh
after_success:
  - git config --global user.email "travis@github-pages" && git config --global user.name "Travis" && yarn gh-pages
env:
  global:
  - COMMIT_AUTHOR_EMAIL: travis@gh-pages
