name: Publish
on: workflow_dispatch
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn test
    - run: yarn build:packages
    - run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
    - run: git remote add upstream git@github.com:BrandwatchLtd/axiom-react.git
    - run: npx lerna publish --conventional-commits --yes --git-remote upstream
