  
name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install --frozen-lockfile
    - run: yarn build:packages
    - run: yarn test
    - run: yarn build:storybook
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  