  
name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build_packages:
    name: 'Build packages'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ github.sha }}
    - run: yarn install --frozen-lockfile
    - run: yarn build:packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    needs: build_packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ github.sha }}
    - run: yarn install --frozen-lockfile
    - run: yarn test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}